### ISSUE TITLE
Can't run using JEST

### ISSUE THREAD

**Issue by avifatal** [extractus/article-extractor#364]
Hi
Im on a nestjs project.
this is how I import the file: `import { ArticleData, extract } from '@extractus/article-extractor';`
I get the error:
```
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /home/avi/work/microservices/node_modules/@extractus/article-extractor/src/main.js:3
    import {
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 17 | import { ArticleData, extract } from '@extractus/article-extractor';
         | ^
      18 |
      19 | @Injectable()
      20 | export class ArticleService {

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (apps/app/src/article.service.ts:17:1)

```
Thanks!

**Comment by ndaidong** [comment]
@avifatal do you specify `"type": "module"` in the package.json file?

**Comment by avifatal** [comment]
@ndaidong but I dont have that. thanks.

**Comment by ndaidong** [comment]
@avifatal yes, maybe that's the cause. Please try again with `"type": "module"` added to enable ESM import/export syntax.
